### PR TITLE
Removing autocomplete for fields and adding second Pro Updater button

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/comet-cache#741

### CODE REVIEW

**Comment by renzms** [comment]
screen shot 2016-06-08 at 12 12 28 am

screen shot 2016-06-08 at 12 13 03 am

**Comment by renzms** [comment]
@raamdev

Ready for review thanks!

**Comment by raamdev** [comment]
Tested and merged. Thank you. 😄

**Comment by renzms** [comment]
@raamdev Updated, thanks!

**Pro Updater Page:**
screen shot 2016-06-17 at 12 30 41 pm

**Options Page:**
screen shot 2016-06-17 at 12 31 07 pm

**Pull request closed without merging**
