### PR TITLE
Add filter to disable clearing cache upon login; 

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/comet-cache#756

### CODE REVIEW

**Comment by raamdev** [comment]
@renzms Were you able to test this with logged-in user caching enabled and [the MU-Plugin filter Jason mentioned](https://github.com/websharks/comet-cache/issues/756#issuecomment-218122286) to confirm that logging in/out does not clear the user cache?

**Comment by renzms** [comment]
> Were you able to test this with logged-in user caching enabled and the MU-Plugin filter Jason mentioned to confirm that logging in/out does not clear the user cache?

Oh you mean this part: 

```
<?php
add_filter('comet_cache_invalidate_when_logged_in_postload', function($invalidate) {
    if (!empty($_POST['action']) && $_POST['action'] === 'login') {
        return $invalidate = false; // Not on this action.
    } else {
        return $invalidate;
    }
});
```

No, not yet, I will have to do that. It didn't occur to me to create an MU Plugin, thought that was an example code of how it was being used.

**Comment by raamdev** [comment]
@renzms Correct. That's how you can test to make sure that what you just committed actually fixes the problem at hand. :-)

**Comment by renzms** [comment]
@raamdev 

- Created the MU plugins folder and included Jason's code in an `s2-hacks.php` file.
- Installed Clean Login plugin as KTS specified here: websharks/comet-cache#756
- Enabled Logged - In User Cache
- Made sure cache was generated first
 
   screen shot 2016-05-11 at 11 39 46 am

  screen shot 2016-05-11 at 11 34 27 am

- Logged out and Logged back in via Clean Login Page Shortcode
- Check if cache was cleared / regenerated

   For the Clean Login Page:
   
screen shot 2016-05-11 at 11 36 53 am

   For a test Post:

screen shot 2016-05-11 at 11 46 34 am

On the backend chart:
screen shot 2016-05-11 at 11 50 38 am


There was no notification on the backend of the cache clearing. Are these the expected results and is there anything I missed to test further?

**Comment by raamdev** [comment]
@renzms As per discussion [here](https://github.com/websharks/comet-cache/issues/756#issuecomment-218607246), could you please update this PR to also include the check for the filter after [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Plugin/WcpUserUtils.php#L43).

Once that's done, you can retest the changes using [the updated filter example](https://github.com/websharks/comet-cache/issues/756#issuecomment-218718426). 

To test that things are behaving properly, please don't rely on the Cache Statistics inside Comet Cache. Instead, generate some user-specific cache files, confirm those cache files exist in the cache directory by using `ls` or `tree`, then logout and login to confirm that the user-specific cache files do not get auto-cleared when the filter is in place.

**Comment by raamdev** [comment]
@renzms Also, you have a bug in the code you already submitted in this PR; you have a space after the first `_` that should not exist: `_ invalidate_when_logged_in_postload`

**Comment by raamdev** [comment]
@renzms I'm going to take this over so I can finish this up in preparation for an RC, which I'd like to do today.

**Comment by renzms** [comment]
> I'm going to take this over so I can finish this up in preparation for an RC, which I'd like to do today.

Alright noted. Thanks!

**Pull request closed without merging**
