### PR TITLE
Shorthand for array(), PHP v5.4+ Codebase Enhancements; 

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/zencache#635

### CODE REVIEW

**Comment by raamdev** [comment]
@renzms This PR has merge conflicts. ↑ Did you merge `000000-dev` before beginning your work and before pushing this?

**Comment by renzms** [comment]
> This PR has merge conflicts. ↑ Did you merge 000000-dev before beginning your work and before pushing this?

Forgot to merge, just did the Pull. 

Can I still follow the steps by GitHub?

```
git fetch origin
git checkout -b feature/635-arrays origin/feature/635-arrays
git merge 000000-dev
```

**Comment by raamdev** [comment]
> Can I still follow the steps by GitHub?

Yes, you can follow those. Just make sure you **DON'T** follow Step 2 provided by GitHub (`git checkout 000000-dev && git merge`) because that will merge your changes into the dev branch, which is what I'm responsible for doing once I've reviewed the changes. :-)

Here's an article Jason recommended for @kristineds when she had merge conflicts recently. I suggest reading it: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

You can also ask @kristineds for some help if you get stuck. She's a master merge-conflict-resolver now. :laughing:

**Comment by renzms** [comment]
> Yes, you can follow those. Just make sure you DON'T follow Step 2 provided by GitHub (git checkout 000000-dev && git merge) because that will merge your changes into the dev branch, which is what I'm responsible for doing once I've reviewed the changes. :-)

I tried step 1, but still says I have merge conflicts? I addressed the merge conflict by trying to resolve the conflict manually as it said it had a problem with 

```
Auto-merging src/includes/closures/Plugin/StatsUtils.php
CONFLICT (content): Merge conflict in src/includes/closures/Plugin/StatsUtils.php
```

**Comment by raamdev** [comment]
@renzms So where else are there merge conflicts?

**Comment by renzms** [comment]
> So where else are there merge conflicts?

@raamdev Head was detached, I fixed that now. In the terminal no merge conflicts exist, but here in GitHub it still says branch has conflicts. Or will that be resolved after you do Step 2?

**Comment by raamdev** [comment]
@renzms When you push your merge conflict fixes to this GitHub branch, GitHub will determine if there are still conflicts with `000000-dev`. As of right now, GitHub is still complaining that there are merge conflicts, which means you need to commit and push your fixes to GitHub.

**Comment by raamdev** [comment]
@renzms I'm going to close this, as the codebase has now been updated to reflect Comet Cache and this PR was submitted against the ZenCache codebase.

**Pull request closed without merging**
