### PR TITLE
Add note when Auto-Cache Engine generates cache file; See: websharks/comet-cache#292

### PR DESCRIPTION
**Pull request by kristineds**
Add note when Auto-Cache Engine generates cache file; 

See: websharks/comet-cache#292

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting my PR for this but it seems like the `via %6$s` on the code is missing on the HTML Note when I tested it? https://github.com/websharks/comet-cache-pro/pull/262/commits/9370deb07cb0988d4972545acc206bc19d584522

- Tested on this page: http://kristine.websharks-inc.net/everyone-loves-cheese/

 screen shot 2016-06-22 at 2 02 52 am

**Comment by raamdev** [comment]
@kristineds writes...
> but it seems like the via %6$s on the code is missing on the HTML Note when I tested it?

How did you test this? How did you build it? Did you make sure that you were running a version of Comet Cache that included your changes in this PR when you were testing?

**Comment by kristineds** [comment]
@raamdev Tested this again and ran `full-build-all`. Seems to be working as expected. 

```
<!-- Comet Cache file path: /cache/comet-cache/cache/http/kristine-websharks-inc-net/index.html -->
<!-- Comet Cache file built for (http://kristine.websharks-inc.net/) in 0.21628 seconds, on: Jun 23rd, 2016 @ 10:19 pm UTC; via HTTP request. -->
<!-- This Comet Cache file will auto-expire (and be rebuilt) on: Jun 30th, 2016 @ 10:19 pm UTC (based on your configured expiration time). -->
```

**Comment by raamdev** [comment]
@kristineds Tested and confirmed working on my end too. Thanks! 👍

**Pull request closed without merging**
