### PR TITLE
Fix bug in backwards compatibility for ZENCACHE_ALLOWED

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/comet-cache#683

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc Quick review when you get a chance please.

**Comment by jaswsinc** [comment]
Looks great! Nice catch on the lowercase issue.

**One suggestion:** Since this runs on every page view, I would try to optimize those calls to `strtoupper()`. It seems easy enough to run that once at the top of this method and then reuse a variable that contains the uppercase version in the rest of the sub-routines.

**Comment by raamdev** [comment]
> Since this runs on every page view, I would try to optimize those calls to strtoupper().

Ah, good idea. Thanks. Done: https://github.com/websharks/comet-cache-pro/commit/367206804724df6a6563ee3996cca685fc56e8f9

**Comment by jaswsinc** [comment]
This looks great to me.

**Pull request closed without merging**
