### PR TITLE
PR: feature/465

### PR DESCRIPTION
**Pull request by jaswsinc**
See: websharks/comet-cache#465

### CODE REVIEW

**Comment by jaswsinc** [comment]
@raamdev This is ready for review.

- I performed some basic tests against WordPress core.
- No tests performed against ManageWP yet however.

**Comment by raamdev** [comment]
Woohoo!! I'll run this through a bunch of tests soon. Awesome work! 😁

**Comment by raamdev** [comment]
When there are no Update Credentials filled in, the "Update Available" link still leads to `/wp-admin/update-core.php`, which is confusing because Comet Cache Pro will not appear in the update list when there are no Update Credentials filled in. 



Maybe the "Update Available" link should instead produce a JavaScript popup message that says to fill in your Update Credentials and save the options first.

**Comment by raamdev** [comment]
@jaswsinc I'm having trouble getting the update notification to show up at all... I built a version of this branch with an old version number (v160701) and I saved my Update Credentials, but nothing shows up as a way for me to update...

**Comment by raamdev** [comment]
## ↑ Scratch that. 

I hit the "Check Again" button on the WordPress Updates page and now the Comet Cache Pro update appears as expected. I guess I just didn't wait long enough for that routine to run via WP Cron.

**Comment by raamdev** [comment]
Tested with ManageWP; works great!

**Comment by jaswsinc** [comment]
> which is confusing because Comet Cache Pro will not appear in the update list when there are no Update Credentials filled in.

Correct.

> Maybe the "Update Available" link should instead produce a JavaScript popup message that says to fill in your Update Credentials and save the options first.

Agree with that idea.

**Comment by jaswsinc** [comment]
I'm taking a closer look at this now.

**Comment by raamdev** [comment]
@jaswsinc If the wrong credentials are entered, or if you have credentials entered and then you clear the credentials after a new version of Comet Cache Pro is detected, attempting to update results in the following confusing and misleading error:



Is there anything we can do to make that message clearer?

**Comment by jaswsinc** [comment]
I'm not sure, but that's a good idea to check. I'd suggest putting that into a new issue and we can investigate to see if there another hook that can use to try and catch a scenario like this in core; i.e., where it uses the details that we are giving it.

**Comment by raamdev** [comment]
> I'd suggest putting that into a new issue

@jaswsinc Done. Thanks! https://github.com/websharks/comet-cache/issues/826

**Comment by raamdev** [comment]
**Comet Cache v160917** has been released and includes changes from this GitHub Issue. See the [v160917 announcement](https://cometcache.com/blog/comet-cache-v160917-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#272).

**Pull request closed without merging**
