### PR TITLE
Adding changes for responsive media queries

### PR DESCRIPTION
**Pull request by renzms**
See websharks/comet-cache#699

### CODE REVIEW

**Comment by raamdev** [comment]
@renzms What is the status on this?

**Comment by renzms** [comment]
@raamdev 

Still in progress, needs more work done as the header area elements gets messy at different browser/device widths. May need to apply something similar to what @jaswsinc did for Comment Mail's header here: https://github.com/websharks/comment-mail-pro/pull/76#issuecomment-229305127

**Comment by raamdev** [comment]
@renzms K. I'm leaving this on the Next Release milestone, so if you could work on this over the next week or two, that would be great.

**Comment by renzms** [comment]
@raamdev 

Copy that. 👍

**Comment by renzms** [comment]
@raamdev 

I have this set for a device/browser width of **480px**, do you think I should have it set at a smaller width and support for **320-360px** width devices? I may need help testing with different devices if so. It's still usable at these smaller widths, however the alignment and center may be a bit off at smaller ranges.

## Original:

- text would run off the side
- buttons and elements unusable
- width of images too large
- panel width too large

screen shot 2016-10-13 at 12 05 48 pm


screen shot 2016-10-13 at 10 30 27 am

## Updated:


- text aligned and centered
- buttons and elements usable 
- width of images auto-resize to browser/device width
- panel width auto-resize to browser/device width

screen shot 2016-10-13 at 12 06 06 pm


screen shot 2016-10-13 at 12 06 17 pm

**Comment by raamdev** [comment]
@renzms I tested the latest changes and things still don't seem to be reflowing properly as I resize my browser. Also, no matter what size I made the browser, I couldn't get the Enable/Disable options to look the way they look in your screenshot. I also noticed inconsistent spacing between the buttons across the top.

**Comment by raamdev** [comment]
@renzms Also note that I pushed [a change](https://github.com/websharks/comet-cache-pro/pull/279/commits/66e7c586387d882f37d23bb5a89514cc1b77f590) to this branch, so you'll want to `git pull` again before making any additional commits.

**Comment by renzms** [comment]
> Also note that I pushed a change to this branch, so you'll want to git pull again before making any additional commits.

Noted. I'll also make some changes to the media queries.

**Comment by renzms** [comment]
@raamdev 

Addressed some inline style elements from the original code, and did some more thorough testing and different widths. Also included the Stats page on this change. Please check, thanks!

### Menu Page

- **Normal**

>screen shot 2016-10-14 at 12 50 54 pm

- **Tablet Width / Horizontal Oriented Device**

>screen shot 2016-10-14 at 12 54 52 pm

- **Mobile Width / Portrait Oriented Device**

>screen shot 2016-10-14 at 12 54 31 pm


### Stats Page

- **Normal**

>screen shot 2016-10-14 at 1 05 51 pm

- **Tablet Width / Horizontal Oriented Device**

>screen shot 2016-10-14 at 1 06 13 pm

- **Mobile Width / Portrait Oriented Device**
>screen shot 2016-10-14 at 1 06 31 pm

**Comment by raamdev** [comment]
@renzms It looks like your last commit reverted the Phings submodule to an older version, undoing the upgrade to the latest Phings module that I pushed to this branch earlier. Please `git pull` and then `git submodule update` on this branch before you do another commit.

I'll do a review of your other changes in a moment.

**Comment by raamdev** [comment]
@renzms I just ran this through some tests and it looks great to me now! :-) Nice work! 

@jaswsinc If you could do a quick code review of this PR and then merge it into `dev` sometime before the RC target (November 11th), that would be great. :-)

**Comment by raamdev** [comment]
@jaswsinc Just confirming you got my last comment above. ↑

**Comment by jaswsinc** [comment]
Received. I will take a look at this soon. 😄

**Pull request merged**
