### PR TITLE
Changes to fix errors when deactivating plugin via Command Line; 

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/comet-cache#728

### CODE REVIEW

**Comment by renzms** [comment]
@jaswsinc / @raamdev 

Ready for review, thanks!

**Comment by raamdev** [comment]
@jaswsinc I reviewed Renz's work here and it appears to match your outline, however while testing this PR I'm stilling getting `'Invalid argument; host token empty!'`:

```
$ wp plugin deactivate comet-cache-pro
PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid argument; host token empty!' in /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php:281
Stack trace:
#0 /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php(61): WebSharks\CometCache\Pro\Classes\AbsBaseAp->deleteFilesFromHostCacheDir('/^.+/i')
#1 /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpUtils.php(95): WebSharks\CometCache\Pro\Classes\AbsBaseAp->clearFilesFromHostCacheDir('/^.+/i')
#2 /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/InstallUtils.php(79): WebSharks\CometCache\Pro\Classes\Plugin->clearCache()
#3 [internal function]: WebSharks\CometCache\Pro\Classes\Plugin->deactivate(false)
#4 /Users/raam/vms/vvv/www/wordpress-default/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
#5 /Use in /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php on line 281
Fatal error: Uncaught exception 'Exception' with message 'Invalid argument; host token empty!' in /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php:281
Stack trace:
#0 /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php(61): WebSharks\CometCache\Pro\Classes\AbsBaseAp->deleteFilesFromHostCacheDir('/^.+/i')
#1 /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpUtils.php(95): WebSharks\CometCache\Pro\Classes\AbsBaseAp->clearFilesFromHostCacheDir('/^.+/i')
#2 /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/InstallUtils.php(79): WebSharks\CometCache\Pro\Classes\Plugin->clearCache()
#3 [internal function]: WebSharks\CometCache\Pro\Classes\Plugin->deactivate(false)
#4 /Users/raam/vms/vvv/www/wordpress-default/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
#5 /Use in /Users/raam/vms/vvv/www/wordpress-default/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php on line 281
```

**Comment by jaswsinc** [comment]
@raamdev I see. Thank you.

## @renzms Suggested Next Step

- After [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Shared/TokenUtils.php#L54) add the following.

  ```php
  if (!$token && $this->isPlugin()) {
      $token = (string) parse_url(home_url(), PHP_URL_HOST);
  }
  ```

**Comment by renzms** [comment]
@raamdev @jaswsinc Updated! Thanks!

**Comment by raamdev** [comment]
Nice! It's working great now!

```
$ wp plugin deactivate comet-cache-pro
Success: Plugin 'comet-cache-pro' deactivated.
```

**Pull request closed without merging**
